# Generated by Django 2.0.5 on 2018-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenSetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodepin', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True)),
                ('avg_voltage', models.IntegerField(default=0)),
                ('avg_current', models.IntegerField(default=0)),
                ('avg_load', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NodePin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodepin', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
